config/routes.rb
Ludditegames::Application.routes.draw do
  resources :products
  resources :cartitems
  
  root :to => 'products#index'
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cartitems, :order => "id DESC"
  has_many :products, :through => :cartitems
  
  attr_accessible :cartitems, :products
  
  def cartitem_for(product)
    cartitem = cartitems.select {|i| i.product == product}.first
	if cartitem.nil?
	  cartitem = Cartitem.new
	  cartitem.product = product
	  cartitem.cart = self
	  cartitem.quantity = 0
	  cartitem.save
	  cartitem.update_attributes({:cart => self, :quantity => 0, :product => product})
	end
	cartitem
  end
  
  def paypal_encrypted(return_url, notify_url)
    # header info to paypal for every cart
	values = {
	  :business => APP_CONFIG[:paypal_email],
	  :cmd => '_cart',
	  :upload => 1,
	  :return => return_url,
	  :notify_url => notify_url,
	  :currency_code => 'GBP',
	  :invoice => id,
	  :cert_id => APP_CONFIG[:paypal_cert_id]
	}
	
	# values for each item in shopping cart
	cartitems.each_with_index do |item, index|
	  values.merge!({
	    "amount_#{index + 1}" => item.product.price,
	    "item_name_#{index + 1}" => item.product.name,
	    "item_number_#{index + 1}" => item.product.id,
	    "quantity_#{index + 1}" => item.quantity
	  })
	end
	
	encrypt_for_paypal(values)
  end

  #magic encryption copied from railscasts #143 paypal security
  PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem") #paypal public key
  APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")       #app public key
  APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")         #app private key
  def encrypt_for_paypal(values)
    signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM), OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), values.map { |k, v| "#{k}=#{v}" }.join("\n"), [], OpenSSL::PKCS7::BINARY)
    OpenSSL::PKCS7::encrypt([OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], signed.to_der, OpenSSL::Cipher::Cipher::new("DES3"), OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
  end 

end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  validates :quantity, :numericality => true, :on => :save
  
  after_initialize :init_quantity
  
  attr_accessible :quantity, :cart, :product, :been_added
  
  def init_quantity
    @quantity = 0
	#self.update_attributes({:quantity => 0 })
  end
  
  def add(more)
    @been_added ||= true
	self.update_attributes({:quantity => self.quantity.to_i + more.to_i })
  end
  
  def been_added
    @been_added
  end
  
end

app/models/product.rb
class Product < ActiveRecord::Base 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # accesses the shopping cart using a session variable
  def current_cart
    @current_cart = session[:cart_id] ? Cart.find(session[:cart_id]) : Cart.create!
	
	if session[:cart_id] != @current_cart.id
	  session[:cart_id] = @current_cart.id
	end

	@current_cart
  end
  
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController

  def create
    product = Product.find(params[:product_id].to_i)
	quantity = params[:quantity].to_i
	quantity ||= 1
	
	cartitem = current_cart.cartitem_for(product)	
	cartitem.add(quantity)
	  
	redirect_to root_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  def index
    @products = Product.all
    @current_cart = current_cart
	
	# return index.html.erb
    respond_to { |f| f.html }
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])

	# return show.html.erb
    respond_to { |f| f.html }
  end

  # GET /products/new
  def new
    @product = Product.new

	# return new.html.erb 
    respond_to { |f| f.html }
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /products/1
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /products/1
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to { |f| f.html { redirect_to products_url } }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # converts markdown text into valid HTML
  def markdown(text)
    #options = [:hard_wrap, :autolink]
    #Redcarpet.new(text, *options).to_html.html_safe
	@markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :hard_wrap => true)
	@markdown.render(text).html_safe
	#Redcarpet.new(text, :hard_wrap => true).to_html.html_safe
  end
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cartitems/_index.html.erb
<% if not current_cart.cartitems.nil? %>
  <table class="table table-condensed">
    <caption>Shopping Cart</caption>
    <% current_cart.cartitems.each do |item| %>
    <tbody>
    <tr>
      <td><%= item.product.name %></td>
	  <td><%= item.quantity %></td>
	  <td><%= item.been_added %></td>
    </tr>
    </tbody>
    <% end %>
  </table>
  <%= form_tag APP_CONFIG[:paypal_url] do %>
    <%= hidden_field_tag :cmd, "_s-xclick" %>
    <%= hidden_field_tag :encrypted, @current_cart.paypal_encrypted("http://www.ludditegames.com","http://www.ludditegames.com") %>
    <%= submit_tag "Checkout", :class => "btn btn-primary" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Ludditegames</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="#">Gabbi's Gameroom</a>
      <ul class="nav">
        <li class="active">
          <a href="#">Home</a>
        </li>
        <li><a href="#">Structure Decks</a></li>
        <li><a href="#">Accessorises</a></li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="hero-unit">
    <h1>Yu-Gi-Oh Cards Here!</h1>
  </div>

  <hr class="soften"/>
  
  <div class="row-fluid">
    <div class="span9">
      <%= yield %>
    </div>
    <div class="span3">
	  <%= render :partial => "cartitems/index", :locals => { :current_cart => @current_cart } %>	
      <h2>About Me</h2>
      <p>I'm Gabbi and I bring you Yu-Gi-Oh cards at near-cost prices!</p>
      <p>Why? Am I totally insane?</p>
      <p>Yes. Yes I am.</p>
      <blockquote>
        <p>You're nuts</p>
        <small>inconcequential person</small>
      </blockquote>
      <p>FUS ROH DAH!</p>
      <blockquote>
        <p>Wow! This is amazing!</p>
        <small>person</small>
      </blockquote>
      <blockquote>
        <p>Gabbi's Gameroom is amazing. Great service, super fast delivery. And I totally didn't get paid for saying this</p>
        <small>person who was not paid anything for this quote</small>
      </blockquote>
      <p>PS. I am always on the lookout for better supplier prices. I don't have that much volume yet
      but if you know anyone, give me a shout at ludditegames@gmail.com</p>
    </div>
  </div>
  
  <hr class="soften"/>

  <footer class="footer">
    <p>Please be aware I only sell to addresses in the UK. This makes it simpler for me in terms of official 
       documents, taxes and legality. This may change if many people email me at ludditegames@gmail.com</p>
    <p>Gabbi's Gameroom is a trading name of Gabbi Ltd. Registered Company No 07909878, VAT number 129 047 026.
       Registered office: 79 Sherrards Way, Barnet, Herts. EN5 2BP</p>
    <p>I fully comply to UK and EU law</p>
</footer>
  
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Product List</h1>

<ul class="thumbnails">
<% @products.each do |product| %>
  <li class="span3">
    <div class="thumbnail">
      <%= image_tag("#{product.image}") %>
	  <h3><%= link_to product.name, product_path(product) %></h3>
	  <p>Gabbi's price: <%= number_to_currency(product.price, :unit => "£") %></p>
	  <%= form_tag cartitems_path, :method => :post do %>
		<%= hidden_field_tag(:quantity, 1) %>
		<%= hidden_field_tag(:product_id, product.id) %>
	    <input id='<%= "add_#{product.id}" %>' type="submit" name="submit" class="btn btn-primary" value="Add to cart"/>
	  <% end %>
    </div>
  </li>
<% end %>
</ul>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<% if @product.nil? == false %>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= markdown @product.description %>
</p>

<p>
  <b>Image:</b>
  <%= @product.image %>
</p>

<p>
  <b>Size:</b>
  <%= @product.size %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |

<% end %>

<%= link_to 'Back', products_path %>